name: Install, Build & Run Cypress

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Cypress
        uses: actions/cache@v1
        id: cypress_cache
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-cypress-
      - name: Cache node_modules
        uses: actions/cache@v1
        id: node_cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Packages
        if: steps.node_cache.outputs.cache-hit != 'true'
        run: yarn
      - name: Build Docz and Run Cypress
        run: yarn test:ci
      - name: Run Unit Tests With Coverage
        run: yarn test:cov
        env:
          CYPRESS_DASHBOARD_KEY: ${{ secrets.CYPRESS_DASHBOARD_KEY }}
          CYPRESS_TEST_USERNAME: ${{ secrets.CYPRESS_TEST_USERNAME }}
          CYPRESS_TEST_PASSWORD: ${{ secrets.CYPRESS_TEST_PASSWORD }}
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
